const BikeData = [
  {
    "ownerID": '6447111b1be67793b7922785',
    "userID": null,
    "image": 'https://example.com/image1.jpg',
    "lat": 34.0522,
    "lon": -118.2437,
    "bikeType": 'Road',
    "timeOut": null,
    "totalStars": 3,
    "lockCombination": 1234,
    "timesUsed": 10,
    "outOfService": false,
    "missing": false,
    "badPW": false,
    "noLock": false,
    "gearIssue": false,
    "flatTire": true,
    "structuralDamage": false,
  },
  {
    ownerID: '6447111b1be67793b7922786',
    userID: null,
    image: 'https://example.com/image2.jpg',
    lat: 37.7749,
    lon: -122.4194,
    bikeType: 'Mountain',
    timeOut: null,
    totalStars: 4,
    lockCombination: 4567,
    timesUsed: 20,
    outOfService: false,
    missing: false,
    badPW: false,
    noLock: false,
    gearIssue: false,
    flatTire: false,
    structuralDamage: false,
  },
  {
    ownerID: '6447111b1be67793b7922787',
    userID: null,
    image: 'https://example.com/image3.jpg',
    lat: 39.7392,
    lon: -104.9903,
    bikeType: 'City',
    timeOut: null,
    totalStars: 5,
    lockCombination: 7890,
    timesUsed: 30,
    outOfService: false,
    missing: false,
    badPW: false,
    noLock: false,
    gearIssue: false,
    flatTire: false,
    structuralDamage: true,
  },
  {
    ownerID: '6447111b1be67793b7922788',
    userID: null,
    image: 'https://example.com/image4.jpg',
    lat: 40.7128,
    lon: -74.006,
    bikeType: 'Road',
    timeOut: null,
    totalStars: 2,
    lockCombination: 2468,
    timesUsed: 40,
    outOfService: false,
    missing: false,
    badPW: false,
    noLock: false,
    gearIssue: true,
    flatTire: false,
    structuralDamage: false,
  },
  {
    ownerID: "6447111b1be67793b7922789",
    userID: null,
    image: "https://example.com/image5.jpg",
    lat: 45.5122,
    lon: -122.6587,
    bikeType: "Mountain Bike",
    timeOut: null,
    totalStars: 4,
    lockCombination: 1745,
    timesUsed: 12,
    outOfService: false,
    missing: false,
    badPW: false,
    noLock: false,
    gearIssue: true,
    flatTire: false,
    structuralDamage: true,
  }
]

export default BikeData;